<?php
/**
 * File: admin/actions/post-comment-action.php
 * Purpose: Synchronizes user dialogue to the ticket registry and logs activity.
 */
ob_start();
session_start();
header('Content-Type: application/json');

require_once('../../../config/config.php');

// 1. 🛡️ Identity Verification
if (!isset($_SESSION['user_id'])) {
    ob_clean();
    http_response_code(401);
    echo json_encode(['success' => false, 'error' => 'Protocol Violation: Active session required.']);
    exit;
}

// 2. 🔍 Input Extraction & Validation
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $ticketId = isset($_POST['ticket_id']) ? intval($_POST['ticket_id']) : 0;
    $userId   = intval($_SESSION['user_id']);
    $comment  = isset($_POST['comment']) ? trim($_POST['comment']) : '';

    if ($ticketId <= 0 || empty($comment)) {
        ob_clean();
        echo json_encode(['success' => false, 'error' => 'Validation Error: Commentary and Ticket Reference are mandatory.']);
        exit;
    }

    // 3. 🚀 Atomic Synchronization Sequence
    try {
        $connection->begin_transaction();

        // A. Insert Dialogue into Ticket_Comments
        $query = "INSERT INTO Ticket_Comments (ticket_id, user_id, comment, created_at) VALUES (?, ?, ?, NOW())";
        $stmt = $connection->prepare($query);
        
        if (!$stmt) {
            throw new Exception("Engine Preparation Failure: " . $connection->error);
        }

        $stmt->bind_param("iis", $ticketId, $userId, $comment);

        if (!$stmt->execute()) {
            throw new Exception("Execution Failure: " . $stmt->error);
        }
        $stmt->close();

        // B. 📝 Audit Trail: Log the Dialogue Event
        $username = $_SESSION['username'] ?? "User #$userId";
        $logDesc = "Dialogue generated by $username on Ticket #$ticketId.";
        $logQuery = "INSERT INTO activity_log (user_id, action_type, description, created_at) VALUES (?, 'TICKET_COMMENT', ?, NOW())";
        
        if ($logStmt = $connection->prepare($logQuery)) {
            $logStmt->bind_param("is", $userId, $logDesc);
            $logStmt->execute();
            $logStmt->close();
        }

        // 🏆 Success: Commit all changes
        $connection->commit();

        ob_clean();
        echo json_encode([
            'success' => true,
            'message' => 'Dialogue synchronized successfully.',
            'timestamp' => date('M j, g:i a')
        ]);

    } catch (Exception $e) {
        // 🛑 Failure: Rollback
        $connection->rollback();
        
        ob_clean();
        http_response_code(500);
        echo json_encode([
            'success' => false, 
            'error'   => 'System Sync Failure: ' . $e->getMessage()
        ]);
    }
} else {
    ob_clean();
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Protocol Error: Invalid request method.']);
}

// Final Cleanup
$connection->close();
ob_end_flush();
exit();